[package]
name = "prism"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A programming language designed for LLM interactions and probabilistic computing"
build = "build.rs"

[dependencies]
# Core dependencies
miette.workspace = true
thiserror.workspace = true
logos.workspace = true

# Parsing
lalrpop-util.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# HTTP client and async runtime
reqwest.workspace = true
tokio.workspace = true

# Environment and configuration
dotenv.workspace = true

# Math and tensor operations
ndarray.workspace = true

[build-dependencies]
lalrpop.workspace = true

[dev-dependencies]
pretty_assertions = "1.3.0"
tokio-test = "0.4"
 