[package]
name = "prism-lang"
version = "0.1.0"
edition = "2021"
description = "A programming language designed for LLM interactions and probabilistic computing"
authors = ["Prism Team"]
license = "MIT"

[dependencies]
# Parsing and lexing
lalrpop-util = "0.20"
logos = "0.13"
chumsky = "0.9"

# Error handling and reporting
miette = { version = "5.10", features = ["fancy"] }
thiserror = "1.0"

# Tensor operations
ndarray = "0.15"
tch = { version = "0.13", optional = true }  # Make PyTorch optional

# Async runtime
tokio = { version = "1.32", features = ["full"] }

# LLM integrations
reqwest = { version = "0.11", features = ["json"] }

# Utilities
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
lalrpop = "0.20"

[dev-dependencies]
pretty_assertions = "1.4"
test-case = "3.1"

[features]
default = []
pytorch = ["tch"]  # Optional PyTorch support
 